homeassistant:
  enabled: true
advanced:
  network_key:
    - 215
    - 211
    - 219
    - 125
    - 115
    - 148
    - 212
    - 149
    - 196
    - 218
    - 60
    - 79
    - 219
    - 84
    - 160
    - 209
  pan_id: 63856
  ext_pan_id:
    - 156
    - 31
    - 149
    - 172
    - 29
    - 185
    - 105
    - 40
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
frontend:
  enabled: true
  port: 8099
version: 4
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: goofu7xaxai6eiN9Ughaebae3noh3eiP5leebahf3beishei0aeghae8UGh5ahho
serial:
  port: /dev/ttyUSB0
device_options:
  legacy: false
devices:
  '0x8c65a3fffecb194e':
    friendly_name: Kugellampe
  '0x881a14fffe06ab29':
    friendly_name: Stehlampe
    transition: 0.5
  '0x8c65a3fffee907f3':
    friendly_name: Temp Sensor Wohnzimmer
  '0x8c65a3fffee5e64f':
    friendly_name: Temp Sensor Flur
  '0x3425b4fffe12977f':
    friendly_name: Temp Sensor Balkon
  '0xc02cedfffe20dcae':
    friendly_name: Wohnzimmer Deckenlampe
  '0x54ef44100117b5df':
    friendly_name: Wohnzimmer Lichtschalter
  '0x0ceff6fffe77f67b':
    friendly_name: Badezimmerspiegel
  '0x54ef4410011ece44':
    friendly_name: '0x54ef4410011ece44'
  '0x0ceff6fffe674b76':
    friendly_name: Anwesenheit Flur
  '0x3425b4fffe130419':
    friendly_name: Temp Sensor Schlafzimmer
  '0x403059fffe4c3a56':
    friendly_name: Küche 2
  '0x403059fffe4d3e94':
    friendly_name: Küche 1
  '0x403059fffe50c676':
    friendly_name: Küche 3
  '0x0c2a6ffffe655a7d':
    friendly_name: Küche 4
  '0x0ceff6fffe8487c1':
    friendly_name: Heizung Wohnzimmer klein
    thermostat_unit: celsius
  '0x44e2f8fffe0bd851':
    friendly_name: Heizung Wohnzimmer groß
  '0xd44867fffe0616e3':
    friendly_name: Heizung Badezimmer
  '0x54ef4410012905a7':
    friendly_name: Badezimmer Lichtschalter
  '0x54ef4410012b4460':
    friendly_name: Flur 3
    transition: 1
  '0x54ef441001296315':
    friendly_name: Flur1
    transition: 1
  '0x54ef4410012cb3f2':
    friendly_name: Flur 2
    transition: 1
  '0x54ef4410012ca10a':
    friendly_name: Bad 1
    transition: 0.5
  '0x54ef4410012c9066':
    friendly_name: Bad 5
    device_temperature_calibration: ''
    transition: 0.5
  '0x54ef4410012c52c1':
    friendly_name: Bad 3
    transition: 0.5
  '0x54ef4410012c9436':
    friendly_name: Bad 2
    transition: 0.5
  '0x54ef4410012ca6ed':
    friendly_name: Bad 4
    device_temperature_calibration: ''
    transition: 0.5
  '0x0ceff6fffe48a7ad':
    friendly_name: Anwesenheit Bad
  '0x881a14fffe47f853':
    friendly_name: '0x881a14fffe47f853'
  '0x8c65a3fffee4b0d5':
    friendly_name: Büro links 1
  '0x44e2f8fffe191225':
    friendly_name: Büro links 2
  '0x8c65a3fffee4d6bb':
    friendly_name: Büro links 3
  '0xd44867fffe39c467':
    friendly_name: Büro rechts 1
  '0x286847fffe1eac3b':
    friendly_name: Büro rechts 2
  '0x44e2f8fffe20efe9':
    friendly_name: Büro rechts 3
  '0x54ef4410012ea5af':
    friendly_name: Abstellkammer Links
  '0x54ef4410012e8279':
    friendly_name: Abstellkammerrecht
  '0x0ceff6fffe16cd9d':
    friendly_name: Anwesenheit Büro
